<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6627a5e16d74c',
    'title' => 'Configure Multistep Form',
    'fields' => array(
        0 => array(
            'key' => 'field_662a51f8a599e',
            'label' => __('Form Steps', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        1 => array(
            'key' => 'field_6627a79912426',
            'label' => __('Select Post Type', 'modularity-frontend-form'),
            'name' => 'saveToPostType',
            'aria-label' => '',
            'type' => 'posttype_select',
            'instructions' => __('The post type from which the fields should be retrieved; this setting also determines which post type the submission will be saved to.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'allow_in_bindings' => 1,
            'placeholder' => '',
            'disabled' => 0,
            'readonly' => 0,
        ),
        2 => array(
            'key' => 'field_6627a5e312422',
            'label' => __('Add Form Step', 'modularity-frontend-form'),
            'name' => 'formSteps',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Add the steps that should be displayed in this form.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'row',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_6627a6b312423',
            'button_label' => __('Add Step', 'modularity-frontend-form'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_696ddb068d230',
                    'label' => __('Form Step Icon', 'modularity-frontend-form'),
                    'name' => 'formStepIcon',
                    'aria-label' => '',
                    'type' => 'icon',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                1 => array(
                    'key' => 'field_6627a6b312423',
                    'label' => __('Form Step Title', 'modularity-frontend-form'),
                    'name' => 'formStepTitle',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => __('By leaving this blank, the configuration of the fieldgroup will be used.', 'modularity-frontend-form'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                2 => array(
                    'key' => 'field_6627a6e112424',
                    'label' => __('From Step Content', 'modularity-frontend-form'),
                    'name' => 'formStepContent',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => __('By leaving this blank, the configuration of the fieldgroup will be used.', 'modularity-frontend-form'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                3 => array(
                    'key' => 'field_6627a6f212425',
                    'label' => __('Form Step Group', 'modularity-frontend-form'),
                    'name' => 'formStepGroup',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'group_6627a5e16d74c' => __('Configure Multistep Form', 'modularity-frontend-form'),
                        'group_69281214800e9' => __('Testgroup', 'modularity-frontend-form'),
                        'post_title' => __('Post title', 'modularity-frontend-form'),
                        'post_content' => __('Post content', 'modularity-frontend-form'),
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'multiple' => 1,
                    'allow_custom' => 0,
                    'placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'search_placeholder' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
            ),
        ),
        3 => array(
            'key' => 'field_662a5218a599f',
            'label' => __('Submission Configuration', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        4 => array(
            'key' => 'field_68258f85a4ad6',
            'label' => __('Submit to', 'modularity-frontend-form'),
            'name' => 'activeHandlers',
            'aria-label' => '',
            'type' => 'checkbox',
            'instructions' => __('Select where you want the submissions to be stored or sent to.', 'modularity-frontend-form'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'WpDbHandler' => __('Database', 'modularity-frontend-form'),
                'MailHandler' => __('E-Mail', 'modularity-frontend-form'),
                'WebHookHandler' => __('Webhook', 'modularity-frontend-form'),
            ),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'allow_custom' => 0,
            'layout' => 'horizontal',
            'toggle' => 0,
            'save_custom' => 0,
            'custom_choice_button_text' => 'Add new choice',
        ),
        5 => array(
            'key' => 'field_6825e3a7d04ee',
            'label' => __('Data Protection Information', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'MailHandler',
                    ),
                ),
                1 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'WebHookHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('<mark>Some of the selected options to send to will receive all data submitted through the form, including any sensitive information that you may collection. Please ensure that the connected services complies with all relevant data protection regulations, such as GDPR and Schrems II.</mark>', 'modularity-frontend-form'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        6 => array(
            'key' => 'field_6825a840a064b',
            'label' => __('Database', 'modularity-frontend-form'),
            'name' => 'WpDbHandlerConfig',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Select where we should store the answers on this form, and with what default status.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'WpDbHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_662a4f4d25fe6',
                    'label' => __('Save as Post Status', 'modularity-frontend-form'),
                    'name' => 'saveToPostTypeStatus',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('The post status to use when a form hasen\'t been reviewed by the user.', 'modularity-frontend-form'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'draft' => __('Draft', 'modularity-frontend-form'),
                        'pending' => __('Pending Review', 'modularity-frontend-form'),
                        'private' => __('Private', 'modularity-frontend-form'),
                        'publish' => __('Published', 'modularity-frontend-form'),
                    ),
                    'default_value' => __('draft', 'modularity-frontend-form'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                ),
            ),
        ),
        7 => array(
            'key' => 'field_6825aeb2d29fb',
            'label' => __('Email', 'modularity-frontend-form'),
            'name' => 'MailHandlerConfig',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Configure the email adresses that should recive the form submission automatically.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'MailHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6825aed6d29fe',
                    'label' => __('Add Reciver', 'modularity-frontend-form'),
                    'name' => 'Recivers',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_repeater_stylised_button' => 0,
                    'layout' => 'row',
                    'pagination' => 0,
                    'min' => 1,
                    'max' => 15,
                    'collapsed' => 'field_6825af0bd29ff',
                    'button_label' => __('Add Reciver', 'modularity-frontend-form'),
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_6825af0bd29ff',
                            'label' => __('Email', 'modularity-frontend-form'),
                            'name' => 'Email',
                            'aria-label' => '',
                            'type' => 'email',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_6825aed6d29fe',
                        ),
                    ),
                ),
            ),
        ),
        8 => array(
            'key' => 'field_6825c6bf45c50',
            'label' => __('Webhook', 'modularity-frontend-form'),
            'name' => 'WebHookHandlerConfig',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Configure a web adress that can recive post data.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'WebHookHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6825c72345c53',
                    'label' => __('Callback URL', 'modularity-frontend-form'),
                    'name' => 'callbackUrl',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        9 => array(
            'key' => 'field_662a5230a59a0',
            'label' => __('Form Completion', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        10 => array(
            'key' => 'field_664de6eb4fffd',
            'label' => __('Enable summary', 'modularity-frontend-form'),
            'name' => 'hasSummaryStep',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('Wheter this form should include a summary step before acquiring the final post status.', 'modularity-frontend-form'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        11 => array(
            'key' => 'field_664de74a4fffe',
            'label' => __('Summary Title', 'modularity-frontend-form'),
            'name' => 'summaryTitle',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_664de6eb4fffd',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        12 => array(
            'key' => 'field_664de76b4ffff',
            'label' => __('Summary Lead', 'modularity-frontend-form'),
            'name' => 'summaryLead',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_664de6eb4fffd',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        13 => array(
            'key' => 'field_662a6546a687a',
            'label' => __('Security', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        14 => array(
            'key' => 'field_662a6557a687b',
            'label' => __('Public Access', 'modularity-frontend-form'),
            'name' => 'isPublicForm',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('This form may be used by unauthenticated visitors', 'modularity-frontend-form'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        15 => array(
            'key' => 'field_69286e466e006',
            'label' => __('Legal', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        16 => array(
            'key' => 'field_69287218405e9',
            'label' => __('Why are we collecting this data?', 'modularity-frontend-form'),
            'name' => 'dataProcessingCategories',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => __('Describe why we need to collect this data.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'fe-form-data-categories',
            'add_term' => 1,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'checkbox',
            'bidirectional' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'bidirectional_target' => array(
            ),
        ),
        17 => array(
            'key' => 'field_69287054405e8',
            'label' => __('Who will process or have access to the data?', 'modularity-frontend-form'),
            'name' => 'dataProcessingProcessors',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => __('List all entities that will access or process the data, including internal departments as well as any external system providers.', 'modularity-frontend-form'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'fe-form-data-processors',
            'add_term' => 1,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'checkbox',
            'bidirectional' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'bidirectional_target' => array(
            ),
        ),
        18 => array(
            'key' => 'field_69286e646e007',
            'label' => __('For how long should we keep the data submitted in this form?', 'modularity-frontend-form'),
            'name' => 'dataProcessingRetentionTime',
            'aria-label' => '',
            'type' => 'range',
            'instructions' => __('What is the maximum retention period for the data before it is deleted? This function will delete the information completly.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 45,
            'min' => '',
            'max' => 365,
            'step' => '',
            'prepend' => '',
            'append' => __('days', 'modularity-frontend-form'),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-frontend-form',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/frontend-form',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));
}