<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6627a5e16d74c',
    'title' => 'Configure Multistep Form',
    'fields' => array(
        0 => array(
            'key' => 'field_662a51f8a599e',
            'label' => __('Form Steps', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        1 => array(
            'key' => 'field_69c28e849a291',
            'label' => __('Save data to post type', 'modularity-frontend-form'),
            'name' => 'savedatatoposttype',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'allow_in_bindings' => 0,
            'ui_on_text' => __('Yes', 'modularity-frontend-form'),
            'ui_off_text' => __('No', 'modularity-frontend-form'),
            'ui' => 1,
        ),
        2 => array(
            'key' => 'field_6627a79912426',
            'label' => __('Select Post Type', 'modularity-frontend-form'),
            'name' => 'saveToPostType',
            'aria-label' => '',
            'type' => 'posttype_select',
            'instructions' => __('The post type from which the fields should be retrieved; this setting also determines which post type the submission will be saved to.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_69c28e849a291',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'allow_in_bindings' => 1,
            'placeholder' => '',
            'disabled' => 0,
            'readonly' => 0,
            'choices' => array(
                'post' => 'Posts',
                'page' => 'Pages',
                'attachment' => 'Media',
                'place' => 'Places',
                'guide' => 'Guides',
                'news' => 'News',
                'grundskola' => 'Grundskola',
                'forskola' => 'Förskola',
                'jobb' => 'Jobb',
                'initiativ' => 'Initiativ',
                'utstallningar' => 'Utställningar',
                'evenemang' => 'Evenemang',
                'modal-content' => 'Modal Content',
            ),
        ),
        3 => array(
            'key' => 'field_6627a5e312422',
            'label' => __('Add Form Step', 'modularity-frontend-form'),
            'name' => 'formSteps',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Add the steps that should be displayed in this form. A maximum of 9 steps is allowed.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'row',
            'pagination' => 0,
            'min' => 0,
            'max' => 9,
            'collapsed' => 'field_6627a6b312423',
            'button_label' => __('Add Step', 'modularity-frontend-form'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_696ddb068d230',
                    'label' => __('Form Step Icon', 'modularity-frontend-form'),
                    'name' => 'formStepIcon',
                    'aria-label' => '',
                    'type' => 'icon',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                1 => array(
                    'key' => 'field_6627a6b312423',
                    'label' => __('Form Step Title', 'modularity-frontend-form'),
                    'name' => 'formStepTitle',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => __('By leaving this blank, the configuration of the fieldgroup will be used.', 'modularity-frontend-form'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                2 => array(
                    'key' => 'field_6627a6e112424',
                    'label' => __('From Step Content', 'modularity-frontend-form'),
                    'name' => 'formStepContent',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => __('By leaving this blank, the configuration of the fieldgroup will be used.', 'modularity-frontend-form'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                3 => array(
                    'key' => 'field_6627a6f212425',
                    'label' => __('Form Step Group', 'modularity-frontend-form'),
                    'name' => 'formStepGroup',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_69c28e849a291',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'group_6627a5e16d74c' => __('Configure Multistep Form', 'modularity-frontend-form'),
                        'group_651e694d7a010' => __('Elementary school', 'modularity-frontend-form'),
                        'group_6524011f6f467' => __('Notice', 'modularity-frontend-form'),
                        'group_64e84e2b7a8c4' => __('Page fields', 'modularity-frontend-form'),
                        'group_64e6f3b077aa6' => __('Person details', 'modularity-frontend-form'),
                        'group_651e669808174' => __('Pre school', 'modularity-frontend-form'),
                        'group_654b8e292c983' => __('Schools Manager Settings', 'modularity-frontend-form'),
                        'group_68d28e231bbaa' => __('Organizer', 'modularity-frontend-form'),
                        'group_68d28e8bc6408' => __('Presentation', 'modularity-frontend-form'),
                        'post_title' => __('Post title', 'modularity-frontend-form'),
                        'post_content' => __('Post content', 'modularity-frontend-form'),
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'multiple' => 1,
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'ui' => 1,
                    'ajax' => 0,
                    'create_options' => 0,
                    'placeholder' => '',
                    'save_options' => 0,
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                4 => array(
                    'key' => 'field_69c14d4ad0766',
                    'label' => __('Form builder', 'modularity-frontend-form'),
                    'name' => 'formbuilder',
                    'aria-label' => '',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_69c28e849a291',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        'layout_69c14d4e9e93d' => array(
                            'key' => 'layout_69c14d4e9e93d',
                            'name' => 'formbuilder-text',
                            'label' => __('Text', 'modularity-frontend-form'),
                            'display' => 'block',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_69c65bfc2a856',
                                    'label' => 'Hidden id',
                                    'name' => 'hidden_id',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => 'acf-hidden',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                1 => array(
                                    'key' => 'field_69ca2d317ffd0',
                                    'label' => 'Hidden conditional logic',
                                    'name' => 'hidden_conditional_logic',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => 'acf-hidden',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                2 => array(
                                    'key' => 'field_69c29191ea4ec',
                                    'label' => 'General',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                3 => array(
                                    'key' => 'field_69c151b3f9a40',
                                    'label' => 'Name',
                                    'name' => 'name',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                4 => array(
                                    'key' => 'field_69c291baea4ed',
                                    'label' => 'Validation',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                5 => array(
                                    'key' => 'field_69c1645fa027a',
                                    'label' => 'Required',
                                    'name' => 'required',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => false,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => 0,
                                    'message' => '',
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                6 => array(
                                    'key' => 'field_69c29e0e7b03f',
                                    'label' => 'Conditional Logic',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                7 => array(
                                    'key' => 'field_69c29e1b7b040',
                                    'label' => 'Conditional Logic',
                                    'name' => 'conditional_logic',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                                8 => array(
                                    'key' => 'field_69cbdc5871b41',
                                    'label' => 'Operator',
                                    'name' => 'conditional_logic_operator',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '25',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                                9 => array(
                                    'key' => 'field_69cbde0a71b42',
                                    'label' => 'Value',
                                    'name' => 'conditional_logic_value',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '25',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_69ccafc1837cd' => array(
                            'key' => 'layout_69ccafc1837cd',
                            'name' => 'formbuilder-radio',
                            'label' => __('Radio', 'modularity-frontend-form'),
                            'display' => 'block',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_69ccafc1837ce',
                                    'label' => 'Hidden id',
                                    'name' => 'hidden_id',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => 'acf-hidden',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                1 => array(
                                    'key' => 'field_69ccafc1837cf',
                                    'label' => 'Hidden conditional logic',
                                    'name' => 'hidden_conditional_logic',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => 'acf-hidden',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                2 => array(
                                    'key' => 'field_69ccafc1837d0',
                                    'label' => 'General',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                3 => array(
                                    'key' => 'field_69ccafc1837d1',
                                    'label' => 'Name',
                                    'name' => 'name',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                4 => array(
                                    'key' => 'field_69ccaff4837d8',
                                    'label' => 'Options',
                                    'name' => 'options',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => '',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_69ccb015837d9',
                                            'label' => 'Name',
                                            'name' => 'name',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_69ccaff4837d8',
                                        ),
                                    ),
                                ),
                                5 => array(
                                    'key' => 'field_69ccafc1837d2',
                                    'label' => 'Validation',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                6 => array(
                                    'key' => 'field_69ccafc1837d3',
                                    'label' => 'Required',
                                    'name' => 'required',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'allow_in_bindings' => 1,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                7 => array(
                                    'key' => 'field_69ccafc1837d4',
                                    'label' => 'Conditional Logic',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                8 => array(
                                    'key' => 'field_69ccafc1837d5',
                                    'label' => 'Conditional Logic',
                                    'name' => 'conditional_logic',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                                9 => array(
                                    'key' => 'field_69ccafc1837d6',
                                    'label' => 'Operator',
                                    'name' => 'conditional_logic_operator',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '25',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                                10 => array(
                                    'key' => 'field_69ccafc1837d7',
                                    'label' => 'Value',
                                    'name' => 'conditional_logic_value',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '25',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_69d664bee63e6' => array(
                            'key' => 'layout_69d664bee63e6',
                            'name' => 'formbuilder-checkbox',
                            'label' => __('Checkbox', 'modularity-frontend-form'),
                            'display' => 'block',
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_69d664bee63e7',
                                    'label' => 'Hidden id',
                                    'name' => 'hidden_id',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => 'acf-hidden',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                1 => array(
                                    'key' => 'field_69d664bee63e8',
                                    'label' => 'Hidden conditional logic',
                                    'name' => 'hidden_conditional_logic',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => 'acf-hidden',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                2 => array(
                                    'key' => 'field_69d664bee63e9',
                                    'label' => 'General',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                3 => array(
                                    'key' => 'field_69d664bee63ea',
                                    'label' => 'Name',
                                    'name' => 'name',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                4 => array(
                                    'key' => 'field_69d664bee63eb',
                                    'label' => 'Options',
                                    'name' => 'options',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => '',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => array(
                                        0 => array(
                                            'key' => 'field_69d664bee63ec',
                                            'label' => 'Name',
                                            'name' => 'name',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'allow_in_bindings' => 0,
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_69d664bee63eb',
                                        ),
                                    ),
                                ),
                                5 => array(
                                    'key' => 'field_69d664bee63ed',
                                    'label' => 'Validation',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                6 => array(
                                    'key' => 'field_69d664bee63ee',
                                    'label' => 'Required',
                                    'name' => 'required',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'allow_in_bindings' => 1,
                                    'ui' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                7 => array(
                                    'key' => 'field_69d664bee63ef',
                                    'label' => 'Conditional Logic',
                                    'name' => '',
                                    'aria-label' => '',
                                    'type' => 'tab',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'placement' => 'top',
                                    'endpoint' => 0,
                                    'selected' => 0,
                                ),
                                8 => array(
                                    'key' => 'field_69d664bee63f0',
                                    'label' => 'Conditional Logic',
                                    'name' => 'conditional_logic',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                                9 => array(
                                    'key' => 'field_69d664bee63f1',
                                    'label' => 'Operator',
                                    'name' => 'conditional_logic_operator',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '25',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                                10 => array(
                                    'key' => 'field_69d664bee63f2',
                                    'label' => 'Value',
                                    'name' => 'conditional_logic_value',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '25',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'allow_in_bindings' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                    'create_options' => 0,
                                    'save_options' => 0,
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                    'button_label' => __('Add field', 'modularity-frontend-form'),
                    'parent_repeater' => 'field_6627a5e312422',
                ),
            ),
        ),
        4 => array(
            'key' => 'field_662a5218a599f',
            'label' => __('Submission Configuration', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        5 => array(
            'key' => 'field_68258f85a4ad6',
            'label' => __('Submit to', 'modularity-frontend-form'),
            'name' => 'activeHandlers',
            'aria-label' => '',
            'type' => 'checkbox',
            'instructions' => __('Select where you want the submissions to be stored or sent to.', 'modularity-frontend-form'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'WpDbHandler' => __('Database', 'modularity-frontend-form'),
                'MailHandler' => __('E-Mail', 'modularity-frontend-form'),
                'WebHookHandler' => __('Webhook', 'modularity-frontend-form'),
            ),
            'default_value' => array(
            ),
            'return_format' => 'value',
            'allow_custom' => 0,
            'layout' => 'horizontal',
            'toggle' => 0,
            'save_custom' => 0,
            'custom_choice_button_text' => 'Add new choice',
        ),
        6 => array(
            'key' => 'field_6825e3a7d04ee',
            'label' => __('Data Protection Information', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'MailHandler',
                    ),
                ),
                1 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'WebHookHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('<mark>Some of the selected options to send to will receive all data submitted through the form, including any sensitive information that you may collection. Please ensure that the connected services complies with all relevant data protection regulations, such as GDPR and Schrems II.</mark>', 'modularity-frontend-form'),
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        7 => array(
            'key' => 'field_6825a840a064b',
            'label' => __('Database', 'modularity-frontend-form'),
            'name' => 'WpDbHandlerConfig',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Select where we should store the answers on this form, and with what default status.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'WpDbHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_662a4f4d25fe6',
                    'label' => __('Save as Post Status', 'modularity-frontend-form'),
                    'name' => 'saveToPostTypeStatus',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => __('The post status to use when a form hasen\'t been reviewed by the user.', 'modularity-frontend-form'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'draft' => __('Draft', 'modularity-frontend-form'),
                        'pending' => __('Pending Review', 'modularity-frontend-form'),
                        'private' => __('Private', 'modularity-frontend-form'),
                        'publish' => __('Published', 'modularity-frontend-form'),
                    ),
                    'default_value' => __('draft', 'modularity-frontend-form'),
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                ),
            ),
        ),
        8 => array(
            'key' => 'field_6825aeb2d29fb',
            'label' => __('Email', 'modularity-frontend-form'),
            'name' => 'MailHandlerConfig',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Configure the email adresses that should recive the form submission automatically.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'MailHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6825aed6d29fe',
                    'label' => __('Add Reciver', 'modularity-frontend-form'),
                    'name' => 'Recivers',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_repeater_stylised_button' => 0,
                    'layout' => 'row',
                    'pagination' => 0,
                    'min' => 1,
                    'max' => 15,
                    'collapsed' => 'field_6825af0bd29ff',
                    'button_label' => __('Add Reciver', 'modularity-frontend-form'),
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_6825af0bd29ff',
                            'label' => __('Email', 'modularity-frontend-form'),
                            'name' => 'Email',
                            'aria-label' => '',
                            'type' => 'email',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_6825aed6d29fe',
                        ),
                    ),
                ),
            ),
        ),
        9 => array(
            'key' => 'field_6825c6bf45c50',
            'label' => __('Webhook', 'modularity-frontend-form'),
            'name' => 'WebHookHandlerConfig',
            'aria-label' => '',
            'type' => 'group',
            'instructions' => __('Configure a web adress that can recive post data.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_68258f85a4ad6',
                        'operator' => '==',
                        'value' => 'WebHookHandler',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'acfe_seamless_style' => 0,
            'acfe_group_modal' => 0,
            'acfe_group_modal_close' => 0,
            'acfe_group_modal_button' => '',
            'acfe_group_modal_size' => 'large',
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6825c72345c53',
                    'label' => __('Callback URL', 'modularity-frontend-form'),
                    'name' => 'callbackUrl',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),
            ),
        ),
        10 => array(
            'key' => 'field_662a6546a687a',
            'label' => __('Security', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        11 => array(
            'key' => 'field_662a6557a687b',
            'label' => __('Public Access', 'modularity-frontend-form'),
            'name' => 'isPublicForm',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => __('This form may be used by unauthenticated visitors', 'modularity-frontend-form'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        12 => array(
            'key' => 'field_69286e466e006',
            'label' => __('Legal', 'modularity-frontend-form'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        13 => array(
            'key' => 'field_69287218405e9',
            'label' => __('Why are we collecting this data?', 'modularity-frontend-form'),
            'name' => 'dataProcessingCategories',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => __('Describe why we need to collect this data.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'fe-form-data-categories',
            'add_term' => 1,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'checkbox',
            'bidirectional' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'bidirectional_target' => array(
            ),
        ),
        14 => array(
            'key' => 'field_69287054405e8',
            'label' => __('Who will process or have access to the data?', 'modularity-frontend-form'),
            'name' => 'dataProcessingProcessors',
            'aria-label' => '',
            'type' => 'taxonomy',
            'instructions' => __('List all entities that will access or process the data, including internal departments as well as any external system providers.', 'modularity-frontend-form'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'fe-form-data-processors',
            'add_term' => 1,
            'save_terms' => 1,
            'load_terms' => 1,
            'return_format' => 'object',
            'field_type' => 'checkbox',
            'bidirectional' => 0,
            'multiple' => 0,
            'allow_null' => 0,
            'bidirectional_target' => array(
            ),
        ),
        15 => array(
            'key' => 'field_69286e646e007',
            'label' => __('For how long should we keep the data submitted in this form?', 'modularity-frontend-form'),
            'name' => 'dataProcessingRetentionTime',
            'aria-label' => '',
            'type' => 'range',
            'instructions' => __('What is the maximum retention period for the data before it is deleted? This function will delete the information completly.', 'modularity-frontend-form'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 45,
            'min' => '',
            'max' => 365,
            'step' => '',
            'prepend' => '',
            'append' => __('days', 'modularity-frontend-form'),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-frontend-form',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/frontend-form',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'display_title' => '',
));
}