<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_68d545b18c491',
    'title' => __('Mod Frontend Form Title', 'modularity-frontend-form'),
    'fields' => array(
        0 => array(
            'key' => 'field_68d545b220e9e',
            'label' => __('Title', 'modularity-frontend-form'),
            'name' => 'frontend_form_fields_title',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'allow_in_bindings' => 0,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        1 => array(
            'key' => 'field_68d68defafba3',
            'label' => __('Fields', 'modularity-frontend-form'),
            'name' => 'fields',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_flexible_advanced' => 0,
            'layouts' => array(
                'layout_68d68df90bc48' => array(
                    'key' => 'layout_68d68df90bc48',
                    'name' => 'checkbox',
                    'label' => __('Checkbox', 'modularity-frontend-form'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_68d68dfbafba4',
                            'label' => 'Titel',
                            'name' => 'titel',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        1 => array(
                            'key' => 'field_68d6901bafba5',
                            'label' => 'Choices',
                            'name' => 'choices',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'acfe_repeater_stylised_button' => 0,
                            'layout' => 'table',
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'Add Row',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                0 => array(
                                    'key' => 'field_68d69023afba6',
                                    'label' => 'Choice',
                                    'name' => 'choice',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'allow_in_bindings' => 0,
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_68d6901bafba5',
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                    'acfe_flexible_render_template' => false,
                    'acfe_flexible_render_style' => false,
                    'acfe_flexible_render_script' => false,
                    'acfe_flexible_thumbnail' => false,
                    'acfe_flexible_settings' => false,
                    'acfe_flexible_settings_size' => 'medium',
                    'acfe_flexible_modal_edit_size' => false,
                    'acfe_flexible_category' => false,
                ),
                'layout_68d692159cb72' => array(
                    'key' => 'layout_68d692159cb72',
                    'name' => 'email',
                    'label' => __('Email', 'modularity-frontend-form'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_68d6921d9cb74',
                            'label' => 'Title',
                            'name' => 'email',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                    'acfe_flexible_render_template' => false,
                    'acfe_flexible_render_style' => false,
                    'acfe_flexible_render_script' => false,
                    'acfe_flexible_thumbnail' => false,
                    'acfe_flexible_settings' => false,
                    'acfe_flexible_settings_size' => 'medium',
                    'acfe_flexible_modal_edit_size' => false,
                    'acfe_flexible_category' => false,
                ),
            ),
            'min' => '',
            'max' => '',
            'button_label' => __('Add Row', 'modularity-frontend-form'),
            'acfe_flexible_stylised_button' => false,
            'acfe_flexible_hide_empty_message' => false,
            'acfe_flexible_empty_message' => '',
            'acfe_flexible_layouts_templates' => false,
            'acfe_flexible_layouts_previews' => false,
            'acfe_flexible_layouts_placeholder' => false,
            'acfe_flexible_layouts_thumbnails' => false,
            'acfe_flexible_layouts_settings' => false,
            'acfe_flexible_async' => array(
            ),
            'acfe_flexible_add_actions' => array(
            ),
            'acfe_flexible_remove_button' => array(
            ),
            'acfe_flexible_layouts_state' => false,
            'acfe_flexible_modal_edit' => array(
                'acfe_flexible_modal_edit_enabled' => false,
                'acfe_flexible_modal_edit_size' => 'large',
            ),
            'acfe_flexible_modal' => array(
                'acfe_flexible_modal_enabled' => false,
                'acfe_flexible_modal_title' => false,
                'acfe_flexible_modal_size' => 'full',
                'acfe_flexible_modal_col' => '4',
                'acfe_flexible_modal_categories' => false,
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'all',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}