<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_6627a5e16d84f',
    'title' => __('Configure Multistep Form', 'api-event-manager'),
    'fields' => array(
        0 => array(
            'key' => 'field_662a51f8a599e',
            'label' => __('Form Steps', 'api-event-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        1 => array(
            'key' => 'field_6627a5e312422',
            'label' => __('Add Form Step', 'api-event-manager'),
            'name' => 'formSteps',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => __('Add the steps that should be displayed in this form.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'layout' => 'row',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_6627a6b312423',
            'button_label' => __('Add Step', 'api-event-manager'),
            'rows_per_page' => 20,
            'acfe_repeater_stylised_button' => 0,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_6627a6b312423',
                    'label' => __('Form Step Title', 'api-event-manager'),
                    'name' => 'formStepTitle',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => __('By leaving this blank, the configuration of the fieldgroup will be used.', 'api-event-manager'),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                1 => array(
                    'key' => 'field_6627a6e112424',
                    'label' => __('From Step Content', 'api-event-manager'),
                    'name' => 'formStepContent',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => __('By leaving this blank, the configuration of the fieldgroup will be used.', 'api-event-manager'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                2 => array(
                    'key' => 'field_6627a6f212425',
                    'label' => __('Form Step Group', 'api-event-manager'),
                    'name' => 'formStepGroup',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'choices' => array(
                        'group_653a509450198' => __('API Resources: Api-resursfält', 'api-event-manager'),
                        'group_66d0837591221' => __('Audio: Audio module', 'api-event-manager'),
                        'group_56a89f42b432b' => __('BookingFields', 'api-event-manager'),
                        'group_5e1d8f163f200' => __('Contact banner: Modularity Contact Banner', 'api-event-manager'),
                        'group_5805e5dc0a3be' => __('Contacts v2: Contacts', 'api-event-manager'),
                        'group_609b788ad04bb' => __('Curator Social Media: Curator Social Media', 'api-event-manager'),
                        'group_583fe4ee88439' => __('Display events', 'api-event-manager'),
                        'group_62816d604ae46' => __('Divider: Divider', 'api-event-manager'),
                        'group_641c51b765f4b' => __('Email Subscribe: Email Subscribe', 'api-event-manager'),
                        'group_6627a5e16d84f' => __('Event Form: Configure Multistep Form', 'api-event-manager'),
                        'group_5c599a27e446a' => __('Event form', 'api-event-manager'),
                        'group_66436fb1b4f7f' => __('Events: Audience', 'api-event-manager'),
                        'group_66436fdd0f112' => __('Events: Category', 'api-event-manager'),
                        'group_66436b29cfb4f' => __('Events: Contact', 'api-event-manager'),
                        'group_66436bf782af1' => __('Events: Description', 'api-event-manager'),
                        'group_65a115157a046' => __('Events: General', 'api-event-manager'),
                        'group_66436ffb2f075' => __('Events: Price', 'api-event-manager'),
                        'group_661e425070deb' => __('Events: Time &amp; Location', 'api-event-manager'),
                        'group_646c5d26e3359' => __('Exclude title from Google Translate', 'api-event-manager'),
                        'group_5729fc6e03367' => __('Feedback: Feedback data', 'api-event-manager'),
                        'group_5756ce3e48783' => __('Files: Files', 'api-event-manager'),
                        'group_58eb301ecb36a' => __('Form: Form', 'api-event-manager'),
                        'group_acfe_dynamic_form' => __('Forms: Dynamic Form', 'api-event-manager'),
                        'group_5666af6d26b7c' => __('Gallery: Gallery', 'api-event-manager'),
                        'group_63ca5ed0cb7f4' => __('Hero: Display hero as', 'api-event-manager'),
                        'group_614b3f1a751bf' => __('Hero: Hero', 'api-event-manager'),
                        'group_671241997f07d' => __('Hidden Post Status Condition', 'api-event-manager'),
                        'group_654a2a57e6897' => __('Hidden validation', 'api-event-manager'),
                        'group_56c47016ea9d5' => __('Iframe: Iframe settings', 'api-event-manager'),
                        'group_570770ab8f064' => __('Image: Image', 'api-event-manager'),
                        'group_569ceab2c16ee' => __('Index: Index', 'api-event-manager'),
                        'group_569e054a7f9c2' => __('Inlay List: List', 'api-event-manager'),
                        'group_67a6218f4b8a6' => __('Interactive map: Interactive Map', 'api-event-manager'),
                        'group_5948e8bc3bf75' => __('Location', 'api-event-manager'),
                        'group_61bc951d73494' => __('Logotype grid: Logotype grid', 'api-event-manager'),
                        'group_64ff22b117e2c' => __('Manual Input: Manual Input Data', 'api-event-manager'),
                        'group_602400d904b59' => __('Map: Map', 'api-event-manager'),
                        'group_67506ac21d132' => __('Markdown: Markdown', 'api-event-manager'),
                        'group_66c34c64b8d10' => __('Menu: Menu Module', 'api-event-manager'),
                        'group_64a29154aa972' => __('Modal: Modal', 'api-event-manager'),
                        'group_56d83cff12bb3' => __('Navigation settings', 'api-event-manager'),
                        'group_56c33cf1470dc' => __('Notice: Display settings', 'api-event-manager'),
                        'group_591c10ab88d77' => __('Notice: Feedback forwarding', 'api-event-manager'),
                        'group_575a842dd1283' => __('Notice: Notice settings', 'api-event-manager'),
                        'group_64219abb0caec' => __('OpenStreetMap: OpenStreetMap', 'api-event-manager'),
                        'group_6784bb5c51d70' => __('Post Icon', 'api-event-manager'),
                        'group_56a8b4fd3567b' => __('Post or page', 'api-event-manager'),
                        'group_571dfd3c07a77' => __('Posts: Data display', 'api-event-manager'),
                        'group_571e045dd555d' => __('Posts: Data filtering', 'api-event-manager'),
                        'group_571dffc63090c' => __('Posts: Data sorting', 'api-event-manager'),
                        'group_571dfaabc3fc5' => __('Posts: Data source', 'api-event-manager'),
                        'group_630645d822841' => __('Posts: Taxonomies to display', 'api-event-manager'),
                        'group_62a30b29785f0' => __('Products: Products module', 'api-event-manager'),
                        'group_64227d79a7f57' => __('Quicklinks', 'api-event-manager'),
                        'group_59535d940706c' => __('RSS: RSS', 'api-event-manager'),
                        'group_61ea7a87e8e9f' => __('Recommend: Recommendations', 'api-event-manager'),
                        'group_56a8b9eddfced' => __('Script: Embed', 'api-event-manager'),
                        'group_66dffe0be28c1' => __('Search: Search Module', 'api-event-manager'),
                        'group_63ff1e1238bd3' => __('Section card: Card Section Settings', 'api-event-manager'),
                        'group_6154339331c4e' => __('Section full: Full Width Section Settings', 'api-event-manager'),
                        'group_599fddb1da69a' => __('Section split: Split Section Settings', 'api-event-manager'),
                        'group_57060b2076f48' => __('Shortlink: Redirect method', 'api-event-manager'),
                        'group_57051862c4890' => __('Shortlink: Shortlink', 'api-event-manager'),
                        'group_58ecb6b6330f4' => __('Sites: Sites', 'api-event-manager'),
                        'group_56a5e99108991' => __('Slider: Slider', 'api-event-manager'),
                        'group_611cffa40276a' => __('Spacer: Whitespace', 'api-event-manager'),
                        'group_5666a2a71d806' => __('Table: Table Editor', 'api-event-manager'),
                        'group_59f2e69948a47' => __('Testimonial Cards: Testimonial Cards', 'api-event-manager'),
                        'group_5891b49127038' => __('Text: Text options', 'api-event-manager'),
                        'group_59ede2f88a7b5' => __('Timeline: Timeline', 'api-event-manager'),
                        'group_57454ae7b0e9a' => __('Video: Video', 'api-event-manager'),
                        'group_5729f4d3e7c7a' => __('Wordpress Widgets: Wordpress Widget', 'api-event-manager'),
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'multiple' => 1,
                    'allow_custom' => 0,
                    'placeholder' => '',
                    'allow_null' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'search_placeholder' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
                3 => array(
                    'key' => 'field_664dea524e1e2',
                    'label' => __('Display Post title', 'api-event-manager'),
                    'name' => 'formStepIncludesPostTitle',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'is_publicly_hidden' => 0,
                    'is_privately_hidden' => 0,
                    'message' => __('If this step should include a field for the posts title', 'api-event-manager'),
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_6627a5e312422',
                ),
            ),
        ),
        2 => array(
            'key' => 'field_662a5218a599f',
            'label' => __('Submission Configuration', 'api-event-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        3 => array(
            'key' => 'field_6627a79912426',
            'label' => __('Select Post Type', 'api-event-manager'),
            'name' => 'saveToPostType',
            'aria-label' => '',
            'type' => 'posttype_select',
            'instructions' => __('The post type that the user should be able to add to or modify.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'placeholder' => '',
            'disabled' => 0,
            'readonly' => 0,
        ),
        4 => array(
            'key' => 'field_662a4f4d25fe6',
            'label' => __('In Progress Post Status', 'api-event-manager'),
            'name' => 'saveToPostTypeStatus',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('The post status to use when a form hasen\'t been reviewed by the user.', 'api-event-manager'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                'draft' => __('Draft', 'api-event-manager'),
                'pending' => __('Pending Review', 'api-event-manager'),
                'private' => __('Private', 'api-event-manager'),
                'publish' => __('Published', 'api-event-manager'),
            ),
            'default_value' => __('draft', 'api-event-manager'),
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        5 => array(
            'key' => 'field_664cac4d3a132',
            'label' => __('Reviewed Post Status', 'api-event-manager'),
            'name' => 'reviewedPostTypeStatus',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => __('The post status to use when a form have been reviewed by the user.', 'api-event-manager'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'choices' => array(
                'draft' => __('Draft', 'api-event-manager'),
                'pending' => __('Pending Review', 'api-event-manager'),
                'private' => __('Private', 'api-event-manager'),
                'publish' => __('Published', 'api-event-manager'),
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'allow_custom' => 0,
            'search_placeholder' => '',
        ),
        6 => array(
            'key' => 'field_662a5230a59a0',
            'label' => __('Form Completion', 'api-event-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        7 => array(
            'key' => 'field_664de6eb4fffd',
            'label' => __('Enable summary', 'api-event-manager'),
            'name' => 'hasSummaryStep',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'message' => __('Wheter this form should include a summary step before acquiring the final post status.', 'api-event-manager'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        8 => array(
            'key' => 'field_664de74a4fffe',
            'label' => __('Summary Title', 'api-event-manager'),
            'name' => 'summaryTitle',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_664de6eb4fffd',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        9 => array(
            'key' => 'field_664de76b4ffff',
            'label' => __('Summary Lead', 'api-event-manager'),
            'name' => 'summaryLead',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_664de6eb4fffd',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
        10 => array(
            'key' => 'field_662a6546a687a',
            'label' => __('Security', 'api-event-manager'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        11 => array(
            'key' => 'field_662a6557a687b',
            'label' => __('Public Access', 'api-event-manager'),
            'name' => 'isPublicForm',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'is_publicly_hidden' => 0,
            'is_privately_hidden' => 0,
            'message' => __('This form may be used by unauthenticated visitors', 'api-event-manager'),
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-frontend-form',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/frontend-form',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}